### ISSUE TITLE
Clean multi-step configuration

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#982]
**Please describe the problem you are trying to solve.**
Currently the configuration of preCICE is directly tied into the parsing of the XML file.
This consists out of:
* LibXML2 which parses an XML file and uses callbacks for entering/leaving tags.
* The `XMLTag`s and `XMLAttribute`s, which are used to validate the XML and contain information on which `Configuration` callbacks should be dispatched to. The `XMLAttribute` knows how to validate and parse its value to the final type (`int`, `double`, `string`). Both of them also contain documentation.
* The ConfigParser, which uses libxml2 to parse an XML file and dispatches the callbacks from LibXML2 to `Listeners` based on the AST of `XMLTag`s given by the root tag.
* The `Configuration`s, which implement `xml::XMLTag::Listener`, receiving callbacks and build and configuring preCICE objects. They also build the AST of `XMLTag`s and `XMLAttribute`s and hold configured preCICE objects
* The `SolverInterface`, which created the base configuration, runs the ConfigParser on the Configuration (object and file), extracts the required configured objects from the Configuration and finalizes their configuration if required.

**Describe the solution you propose.**
Restructure the parsing to multiple stages:
1. Use LibXML2 to create an XML AST using the callbacks. This simply contains nested tags and attributes.
2. Transform the XML AST to a Configuration AST. This part checks tag occurrence and validates attributes.
3. Transform the Configuration AST to the required preCICE objects using contextual information (participant name, current rank, total ranks).

The benefits of this strategy is:
* Easier to test as stages can be checked separately
* Easier to debug as the output relies only on the input and both can be inspected separately.
* Allows to integrate location information (from the  XML file) for each object in the Configuration AST. This should allow to generate very detailed error messages.
* The configuration AST contains all information, hence the order in the XML will not matter any more.

The downsides are:
* A lot of work
* Spreads out information into the transformation functions and the objects.

Open Questions:
* Where to put the XML documentation?
* How to distribute the information over the packages (`com`, `m2n`, ...)

**Describe alternatives you've considered**
Leave it as it is.

**Comment by uekerman** [comment]
Would this interfere with the localized configuration we have right now? Meaning that each package has its own local configuration? In my opinion this is a very neat feature and a low-entry barrier. I have seen other codes where all configuration routines are in one place -- a nightmare if you want to change sth.

>     The configuration AST contains all information, hence the order in the XML will not matter any more.

What would this imply for cases where the order matters? If I am not mistaking this is currently only the case for compositional coupling schemes.

**Comment by fsimonis** [comment]
> Would this interfere with the localized configuration we have right now? Meaning that each package has its own local configuration?

We should be able to keep the code in the individual packages.

> What would this imply for cases where the order matters?

I was referring to the order of processing. As an example: first data declarations, then mesh declarations, then Participants. And all independent of the order in the XML.

What this means is that we won't run into issues for things like this:

```
<mesh name="SadMesh">
  <use-data name="Below"/>
</mesh>

<data:scalar name="Below">
```

This would even allow us to do things like sorting data and meshes by name to make IDs easier to debug.

**Comment by uekerman** [comment]
> We should be able to keep the code in the individual packages.

That's good. 

> This would even allow us to do things like sorting data and meshes by name to make IDs easier to debug.

I like it.

But we would need to resolve

> What would this imply for cases where the order matters? If I am not mistaking this is currently only the case for compositional coupling schemes.

then, right?

**Comment by fsimonis** [comment]
The order is given by the order in the coupling scheme, correct? In that case we can just keep the order from the config.

**Comment by uekerman** [comment]
> The order is given by the order in the coupling scheme, correct?

It's given by the order **of** he coupling scheme**s**.

**Comment by fsimonis** [comment]
> It's given by the order of the coupling schemes.

There are multiple easy answers to this.
* the XML will still be parsed from front to finish. So individual tags, such as coupling schemes or meshes, will be parsed and hence stored in same order. The difference is that they are independent of other tags. So, we can process all data, then all meshes, then participants, then communication, and finally all coupling schemes.
* we don't mention an order anywhere. It's not documented, let alone guaranteed. So, we could even reorder them as a post processing step.

**Comment by fsimonis** [comment]
A concrete example of how these stages would look like based on the smallest config I could find in the tutorials, the channel-transport case.

## Configuration

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
  <data:vector name="Velocity" />

  <mesh name="Fluid-Mesh" dimensions="2">
    <use-data name="Velocity" />
  </mesh>

  <mesh name="Transport-Mesh" dimensions="2">
    <use-data name="Velocity" />
  </mesh>

  <participant name="Fluid">
    <provide-mesh name="Fluid-Mesh" />
    <receive-mesh name="Transport-Mesh" from="Transport" />
    <write-data name="Velocity" mesh="Fluid-Mesh" />
    <mapping:rbf direction="write" from="Fluid-Mesh" to="Transport-Mesh" constraint="consistent">
      <basis-function:compact-tps-c2 support-radius="0.4" />
    </mapping:rbf>
  </participant>

  <participant name="Transport">
    <provide-mesh name="Transport-Mesh" />
    <read-data name="Velocity" mesh="Transport-Mesh" />
  </participant>

  <m2n:sockets acceptor="Fluid" connector="Transport" exchange-directory=".." />

  <coupling-scheme:serial-explicit>
    <time-window-size value="0.005" />
    <max-time value="1.0" />
    <participants first="Fluid" second="Transport" />
    <exchange data="Velocity" mesh="Transport-Mesh" from="Fluid" to="Transport" />
  </coupling-scheme:serial-explicit>
</precice-configuration>
```

## XML AST

Result of parsing the XML file.

```cpp
struct TAG {
   string name;
   map<string, string> attributes;
   vector<TAG> subtags;
};
```

```
TAG precice-configuration
    TAG data:vector name="Velocity

    TAG mesh name="Fluid-Mesh" dimensions="2"
        TAG use-data name="Velocity"

    TAG mesh name="Transport-Mesh" dimensions="2"
        TAG use-data name="Velocity"

    TAG participant name="Fluid"
        TAG provide-mesh name="Fluid-Mesh"
        TAG receive-mesh name="Transport-Mesh" from="Transport"
        TAG write-data name="Velocity" mesh="Fluid-Mesh"
        TAG mapping:rbf direction="write" from="Fluid-Mesh" to="Transport-Mesh" constraint="consistent">
            TAG basis-function:compact-tps-c2 support-radius="0.4"

    TAG participant name="Transport">
        TAG provide-mesh name="Transport-Mesh"
        TAG read-data name="Velocity" mesh="Transport-Mesh"

    TAG m2n:sockets acceptor="Fluid" connector="Transport" exchange-directory=".."

    TAG coupling-scheme:serial-explicit>
        TAG time-window-size value="0.005"
        TAG max-time value="1.0"
        TAG participants first="Fluid" second="Transport"
        TAG exchange data="Velocity" mesh="Transport-Mesh" from="Fluid" to="Transport"
```

## Configuration

The XML AST is processed by a configurator, which takes an XML tag, checks and converts datatypes, checks how often a tag may appear and produces a configuration. This needs to recourse.

Examples:
* `TAG data:vector name="Velocity"` becomes `config::VectorData{"Velocity"}`.
* `TAG mesh name="Fluid-Mesh" dimensions="2"` becomes `config::Mesh{"Fluid-Mesh", 2, ...}`

This is a yamlified version of the output.

```yaml
Configuration:
  Data:
    - type: Vector
      name: "Velocity"

  Meshes:
    - name: "Fluid-Mesh"
      dimensions: 2
      data:
        - "Velocity"
    - name: "Transport-Mesh"
      dimensions: 2
      data:
        - "Velocity"

  Participants:
    - name: "Fluid"
      provides:
        - "Fluid-Mesh"
      receives:
        - name: "Transport-Mesh"
          from: "Transport"
      writes:
        - name: "Velocity"
          mesh: "Fluid-Mesh"

      mappings:
        - type: rbf
          direction: "write"
          from: "Fluid-Mesh"
          to: "Transport-Mesh"
          constraint: "consistent"
          basis-function:
            type: compact-tps-c2
            support-radius: 0.4

    - name: "Transport"
      provides:
        - "Transport-Mesh"
      reads:
        - name: "Velocity"
          mesh: "Transport-Mesh"

    M2Ns:
      - type: sockets
        acceptor: "Fluid"
        connector: "Transport"
        exchange-directory: ".."

    CouplingSchemes:
      - type: serial-explicit
        time-window-size: 0.005
        max-time: 1.0
        participants:
          first: "Fluid"
          second: "Transport"
        exchange:
        - data: "Velocity"
          mesh: "Transport-Mesh"
          from: "Fluid"
          to: "Transport"
```

## Checks

Now that we have an AST of the configuration, we can apply a list of structured checks.
* Are Data names unique (runs on the root config)
* Are Mesh names unique (runs on the root config)
* Do all meshes specify data to use (runs on the Mesh config)
* Do data in Meshes exist (runs on the root config)

## The participant

The final step is to instantiate a Participant from the config given the name, rank and size passed via the constructor.
